String getMappingMessage(String key) => messageMap[key] ?? key;

final messageMap = {
  "rollcall_closed": "二维码签到已结束",
  "device_used": "该设备已签到，请更换设备重新扫描",
  "QR_code_expired": "签到二维码已过期",
  "unknown_student": "您还不是本课学生，请先加入课程",
  "failed": "签到失败，请及时告知老师",
  "wrongNumberCode": "签到密码错误，请重试",
  "rollcallFinished": "签到失败，点名已结束",
  "getPositionFailed": "获取位置信息失败",
  "getPositionFailedTimeout": "获取位置信息超时",
  "getPositionFailedPermissionDeined": "没有权限获取定位信息",
  "getPositionFailedUnavailable": "获取定位信息功能不可用",
  "retry": "签到失败，请重试",
  "outofScope": "当前定位信息获取异常，可能导致签到失败，请尝试重新签到",
  "fetchStudentsError": "学生信息获取失败，请稍后重试",
  "deviceAlreadyInUse": "已有学生使用该设备签到，请更换设备再试",
  "answer": "去签到",
  "answered": "已签到",
  "updatedAt": "最后修改时间",
  "inProgress": "进行中",
  "searchPlaceholder": "姓名/人员编号",
  "discardChangesConfirm": "点名结果已更改，是否保存？",
  "deleteConfirm": "是否删除此点名？",
  "history": "点名记录",
  "haveRollcallInProgress": "已有进行中的点名，将自动进入",
  "success": "签到成功",
  "pleaseInputPassword": "请输入签到密码",
  "rollcallCode": "签到密码",
  "noTimeLimit": "不限时",
  "absent": "未到",
  "numberRollcallInProgressJoinConfirm": "数字点名正在进行，是否签到？",
  "total": "全部",
  "radarToggleTip": "你需要开启位置才能点名哦!",
  "doNotLeaveAnswerPage": "正在尝试签到，请勿离开此页面",
  "noRollcallRecord": "没有任何点名记录",
  "notCreateRollcall": "课程在此时间内无课表信息，无法发起点名",
};
